added p2p chat
wimag/AUSD pull request #3
Opened 2017-01-14 17:36 UTC by wimag

@yurii-litvinov  Добавил p2p chat. Это сильно упрощенная версия проекта, который я делал летом https://github.com/JetBrains/p2p-games (точнее его небольшое подмножество). 

возможно оно не работает по Windows (проблема с двойным биндом портов), но я там его не запускал.

Текстовое описание модулей есть среди описания того проекта. Если надо - перенесу сюда https://github.com/JetBrains/p2p-games/wiki/Managers

2017-01-16 09:31 UTC, yurii-litvinov requested changes
- Папка .gradle не нужна
- Сгенерированные protoc файлы тоже, в общем-то, не нужны, лучше автоматически генерить их во время сборки (https://github.com/google/protobuf-gradle-plugin)
- Без некоторых ручных манипуляций не собираются тесты
- Под виндой действительно не работает, `java.net.SocketException: Cannot assign requested address: no further information: localhost/127.0.0.1:8892` на `bootstrap.connect(host, addr)` в MessageClient, но ладно, это можно не править.

2017-01-16 09:31 UTC, yurii-litvinov commented on P2P Chat/src/main/kotlin/broker/GroupBroker.kt
> +interface GroupBroker {
Мне кажется, важные для системы интерфейсы точно нуждаются в комментариях

2017-01-19 18:33 UTC, wimag commented
Добавил/исправил большую часть комментариев. 
Пофиксил тесты (наверное) - похоже была проблема с импортом
Убрал папку .gradle

А вот протобаф плагин у меня так и не завелся (сыпет тонну ошибок)

2017-01-20 21:01 UTC, yurii-litvinov commented
Да, прямо из коробки оно не работает (вот багрепорт: https://github.com/google/protobuf-gradle-plugin/issues/100), но если добавить 
```
compileKotlin {
	dependsOn(':generateProto')
}
```
то задачи запустятся в правильном порядке и всё-таки всё соберётся (главное, чтобы версии protoc, качаемого из интернета, и protobuf-java совпадали, я вот долго не мог понять, почему оно не собирается).

Ну хорошо, зачтена.

2017-01-20 23:50 UTC, merged